workflows:
  ios_capacitor_testflight:
    name: iOS Capacitor TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - appstore_credentials
        - ios_config
      vars:
        APP_VERSION: "1.0.0"
        TEAM_ID: "NWGUYF42KW"
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        BUNDLE_ID: com.apex.tradeline
      xcode: "16.0"
      cocoapods: "default"
      node: "20.11.1"
      npm: "10"
    scripts:
      - name: Resolve version/build
        script: |
          set -euo pipefail
          : "${APP_VERSION:=1.0.0}"
          APP_BUILD="$(date +%y%m%d%H%M)"
          {
            echo "APP_VERSION=$APP_VERSION"
            echo "APP_BUILD=$APP_BUILD"
          } >> "$CM_ENV"
      - name: Install npm dependencies
        script: npm ci
      - name: Build web assets
        script: npm run build
      - name: Verify web build artifacts
        script: |
          #!/bin/bash
          set -euo pipefail
          if [[ ! -f dist/index.html ]]; then
            echo "Missing dist/index.html after npm run build" >&2
            exit 1
          fi
      - name: Sync Capacitor iOS wrapper
        script: npx --yes cap sync ios
      - name: Verify iOS project exists
        script: |
          #!/bin/bash
          set -euo pipefail
          PROJECT_FILE="ios/App/App.xcodeproj/project.pbxproj"
          WORKSPACE_PATH="${XCODE_WORKSPACE:-ios/App/App.xcworkspace}"
          WORKSPACE_FILE="${WORKSPACE_PATH%/}/contents.xcworkspacedata"

          missing=0
          if [[ ! -f "$PROJECT_FILE" ]]; then
            echo "Expected $PROJECT_FILE to exist after Capacitor sync" >&2
            missing=1
          fi
          if [[ ! -f "$WORKSPACE_FILE" ]]; then
            echo "Expected $WORKSPACE_FILE to exist after Capacitor sync" >&2
            missing=1
          fi

          if (( missing )); then
            echo "Run 'npx cap add ios' locally and commit the ios/App wrapper." >&2
            exit 1
          fi
      - name: Verify signing environment
        script: |
          #!/bin/bash
          set -euo pipefail

          TEAM_ID="${TEAM_ID:-NWGUYF42KW}"
          export TEAM_ID

          missing=()
          for var in APP_STORE_CONNECT_KEY_IDENTIFIER APP_STORE_CONNECT_ISSUER_ID APP_STORE_CONNECT_PRIVATE_KEY; do
            if [[ -z "${!var:-}" ]]; then
              missing+=("$var")
            fi
          done

          if (( ${#missing[@]} )); then
            printf 'Missing required environment variables: %s\n' "${missing[*]}" >&2
            echo "Populate the ios_config (TEAM_ID) and appstore_credentials groups in Codemagic." >&2
            exit 1
          fi

          printf 'TEAM_ID=%s\n' "$TEAM_ID" >> "$CM_ENV"
      - name: Install CocoaPods dependencies
        script: |
          set -euo pipefail
          cd ios/App
          pod install
      - name: Prepare export options
        script: |
          cat <<'PLIST' > "$CM_BUILD_DIR/ExportOptions.plist"
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>uploadBitcode</key>
              <false/>
              <key>compileBitcode</key>
              <true/>
              <key>destination</key>
              <string>export</string>
              <key>manageAppVersionAndBuildNumber</key>
              <true/>
            </dict>
          </plist>
          PLIST
      - name: Archive iOS build
        script: |
          #!/bin/bash
          set -euo pipefail
          WORKSPACE_PATH="${XCODE_WORKSPACE:-ios/App/App.xcworkspace}"
          WORKSPACE_DIR="$(dirname "$WORKSPACE_PATH")"
          WORKSPACE_NAME="$(basename "$WORKSPACE_PATH")"
          SCHEME_NAME="${XCODE_SCHEME:-App}"
          BUNDLE_ID_VALUE="${BUNDLE_ID:-com.apex.tradeline}"

          cd "$WORKSPACE_DIR"
          xcodebuild \
            -workspace "$WORKSPACE_NAME" \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="${TEAM_ID}" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID_VALUE" \
            MARKETING_VERSION="$APP_VERSION" \
            CURRENT_PROJECT_VERSION="$APP_BUILD" \
            clean archive
      - name: Export IPA
        script: |
          set -euo pipefail
          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/export"
    artifacts:
      - $CM_BUILD_DIR/App.xcarchive
      - $CM_BUILD_DIR/export/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
