workflows:
  ios_capacitor_testflight:
    name: iOS Capacitor TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - ios_config
        - appstore_credentials
      node: "18.20.0"
      cocoapods: "1.12.1"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
      vars:
        APP_VERSION: "1.0.0"
        APP_BUILD: "1003"
    scripts:
      - name: Install npm deps
        script: |
          set -euo pipefail
          npm ci
      - name: Build web app
        script: |
          set -euo pipefail
          npm run build
      - name: Ensure iOS platform and sync
        script: |
          set -euo pipefail
          if [ ! -d ios ]; then
            npx cap add ios
          fi
          npx cap sync ios
      - name: Update version numbers
        script: |
          set -euo pipefail
          cd ios/App
          # Update MARKETING_VERSION and CURRENT_PROJECT_VERSION in project.pbxproj
          sed -i '' "s/MARKETING_VERSION = .*/MARKETING_VERSION = ${APP_VERSION};/g" App.xcodeproj/project.pbxproj
          sed -i '' "s/CURRENT_PROJECT_VERSION = .*/CURRENT_PROJECT_VERSION = ${APP_BUILD};/g" App.xcodeproj/project.pbxproj
          echo "✅ Updated version to ${APP_VERSION} (${APP_BUILD})"
          # Verify changes
          grep -A 2 "MARKETING_VERSION" App.xcodeproj/project.pbxproj | head -4
      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios/App
          pod install
      - name: Setup iOS signing
        script: |
          set -euo pipefail
          xcode-project use-profiles
      - name: Build .ipa for TestFlight
        script: |
          set -euo pipefail
          xcode-project build-ipa \
            --workspace $XCODE_WORKSPACE \
            --scheme $XCODE_SCHEME \
            --config Release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        # Codemagic publishing section doesn't support env var references for api_key auth
        # Must use 'integration' method which uses team-level App Store Connect integration
        # Your credentials from appstore_credentials group should be added to:
        # Codemagic → Team settings → Team integrations → App Store Connect
        auth: integration
        submit_to_testflight: true
