workflows:
  ios_capacitor_testflight:
    name: iOS Capacitor → TestFlight (No Mac)
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app-store
      vars:
        MARKETING_VERSION: "1.0.0"         # bump as needed
        BUILD_NUMBER: "1007"               # must be > last TestFlight build
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      groups:
        - appstore_connect                 # set in Codemagic UI
    triggering:
      events: [ manual ]

    scripts:
      - name: Install Node deps & build web
        script: |
          if [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i && pnpm build;
          elif [ -f yarn.lock ]; then yarn install --frozen-lockfile && yarn build;
          else npm ci && npm run build; fi

      - name: Capacitor sync iOS
        script: |
          npx cap sync ios

      - name: CocoaPods (if Podfile exists)
        script: |
          if [ -f ios/App/Podfile ]; then
            gem install cocoapods -N
            cd ios/App && pod repo update && pod install
          fi

      - name: Bump Info.plist (no agvtool)
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $MARKETING_VERSION" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/App/App/Info.plist

      - name: Archive (device build)
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/TradeLine247.xcarchive" \
            clean archive CODE_SIGN_STYLE=Automatic | xcpretty

      - name: Export IPA (App Store)
        script: |
          cat > $CM_BUILD_DIR/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>app-store</string>
            <key>compileBitcode</key><false/>
            <key>uploadSymbols</key><true/>
            <key>signingStyle</key><string>automatic</string>
            <key>destination</key><string>export</string>
          </dict></plist>
          EOF
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/TradeLine247.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/export" | xcpretty

      - name: Publish to TestFlight (ASC API key)
        script: |
          cm-publish-app-store-connect \
            --path "$CM_BUILD_DIR/export/*.ipa" \
            --bundle-id "$BUNDLE_ID" \
            --submit-for-beta-review false

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/TradeLine247.xcarchive

    publishing:
      app_store_connect:
        auth: api_key
