workflows:
  ios_capacitor_testflight:
    name: iOS Capacitor TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - appstore_credentials
      node: "18.20.0"
      cocoapods: "1.12.1"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.apex.tradeline
      vars:
        APP_VERSION: "1.0.0"
    scripts:
      - name: Install npm dependencies
        script: |
          set -euo pipefail
          : "${APP_VERSION:=1.0.0}"
          APP_BUILD="$(date +%y%m%d%H%M)"
          {
            echo "APP_VERSION=$APP_VERSION"
            echo "APP_BUILD=$APP_BUILD"
          } >> "$CM_ENV"
      - name: Install npm dependencies
        script: npm ci
      - name: Build web assets
        script: npm run build
      - name: Sync iOS wrapper & install pods
        script: |
          set -euo pipefail
          bash ./scripts/ci-ios-setup.sh
      - name: Prepare export options
        script: |
          cat <<'PLIST' > "$CM_BUILD_DIR/ExportOptions.plist"
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>uploadBitcode</key>
              <false/>
              <key>compileBitcode</key>
              <true/>
              <key>destination</key>
              <string>export</string>
              <key>manageAppVersionAndBuildNumber</key>
              <true/>
            </dict>
          </plist>
          PLIST
      - name: Archive iOS build
        script: |
          set -euo pipefail
          # Apply provisioning profiles and certificates
          xcode-project use-profiles
      - name: Build iOS App Archive
        script: |
          set -euo pipefail
          # Build the app and create an .ipa archive
          xcode-project build-ipa --workspace ios/App/App.xcworkspace --scheme App
    publishing:
      app_store_connect:
        auth: api_key
        key_id: $KEY_ID
        issuer_id: $ISSUER_ID
        api_key: $PRIVATE_KEY
        submit_to_testflight: true
