      - name: Ensure iOS platform (idempotent + self-heal)
        script: |
          set -euo pipefail
          PROJ_DIR="ios/App"
          XCPROJ="$PROJ_DIR/App.xcodeproj"
          XCWORK="$PROJ_DIR/App.xcworkspace"

          if [[ -d "$XCPROJ" || -d "$XCWORK" ]]; then
            echo "✅ Found Xcode project/workspace — nothing to add."
          else
            if [[ -d ios ]]; then
              echo "⚠️  'ios/' exists but no Xcode project — recreating Capacitor iOS platform"
              rm -rf ios
            fi
            echo "🆕 Adding iOS platform..."
            npm i -D @capacitor/ios
            npx cap add ios
          fi

      - name: Sync iOS & CocoaPods
        script: |
          set -euo pipefail
          # Sync web assets + native deps
          npx cap sync ios

          # CocoaPods install
          cd ios/App
          command -v pod >/dev/null 2>&1 || sudo gem install cocoapods --no-document
          pod repo update || true
          pod install --repo-update

          # Sanity: workspace must exist after pods
          test -d App.xcworkspace || { echo "❌ CocoaPods didn't produce App.xcworkspace"; exit 1; }
