workflows:
  ios_capacitor_testflight:
    name: iOS Capacitor TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - appstore_credentials
      node: "18.20.0"
      cocoapods: "1.12.1"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.apex.tradeline
      vars:
        APP_VERSION: "1.0.0"
    scripts:
      - name: Install npm dependencies
        script: |
          set -euo pipefail
          # Install Node.js dependencies
          npm ci
      - name: Ensure iOS platform and update
        script: |
          set -euo pipefail
          # If iOS platform is not added, add it
          if [ ! -d ios ]; then
            npx cap add ios
          fi
          # Sync Capacitor project: install plugins and copy web assets
          npx cap sync ios
      - name: Install iOS CocoaPods dependencies
        script: |
          set -euo pipefail
          # Navigate to iOS project directory and install CocoaPods
          cd ios/App
          pod install
      - name: Set up code signing on Xcode project
        script: |
          set -euo pipefail
          # Apply provisioning profiles and certificates
          xcode-project use-profiles
      - name: Build iOS App Archive
        script: |
          set -euo pipefail
          # Build the app and create an .ipa archive
          xcode-project build-ipa --workspace ios/App/App.xcworkspace --scheme App
    publishing:
      app_store_connect:
        auth: api_key
        key_id: $KEY_ID
        issuer_id: $ISSUER_ID
        api_key: $PRIVATE_KEY
        submit_to_testflight: true
