workflows:
  ios_capacitor_testflight:
    name: iOS Capacitor TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - appstore_credentials
      node: "18.20.0"
      cocoapods: "1.12.1"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.apex.tradeline
      vars:
        APP_VERSION: "1.0.0"
        APP_BUILD: "1003"
    scripts:
      - name: Install npm dependencies
        script: |
          set -euo pipefail
          npm ci
      - name: Build web app
        script: |
          set -euo pipefail
          npm run build
      - name: Ensure iOS platform and sync
        script: |
          set -euo pipefail
          if [ ! -d ios ]; then
            npx cap add ios
          fi
          npx cap sync ios
      - name: Update version numbers
        script: |
          set -euo pipefail
          cd ios/App
          # Update MARKETING_VERSION and CURRENT_PROJECT_VERSION in project.pbxproj
          sed -i '' "s/MARKETING_VERSION = .*/MARKETING_VERSION = ${APP_VERSION};/g" App.xcodeproj/project.pbxproj
          sed -i '' "s/CURRENT_PROJECT_VERSION = .*/CURRENT_PROJECT_VERSION = ${APP_BUILD};/g" App.xcodeproj/project.pbxproj
          echo "✅ Updated version to ${APP_VERSION} (${APP_BUILD})"
          # Verify changes
          grep -A 2 "MARKETING_VERSION" App.xcodeproj/project.pbxproj | head -4
      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios/App
          pod install
      - name: Setup signing
        script: |
          set -euo pipefail
          xcode-project use-profiles
      - name: Build .ipa
        script: |
          set -euo pipefail
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --config Release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
