name: ios / Build & Upload (manual)

on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Upload is handled by Codemagic (App Store Connect API key). Trigger only if needed."
