name: ios / Build & Upload

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-ios:
    name: ios/build
    runs-on: macos-14
    timeout-minutes: 45

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Sync Capacitor iOS project
        run: npx cap sync ios

      - name: Install CocoaPods dependencies
        run: pod install
        working-directory: ios/App

      - name: Build iOS workspace
        run: |
          set -o pipefail
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
        working-directory: ios/App
