name: ios / Build & Upload (manual)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 45
    env:
      BASE_URL: https://www.tradeline247ai.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build web assets
        run: npm run build

      - name: Sync Capacitor iOS project
        run: npx cap sync ios

      - name: Ensure CocoaPods is available
        run: |
          if ! command -v pod >/dev/null 2>&1; then
            sudo gem install cocoapods --no-document
          fi
          pod --version

      - name: Install iOS pods
        working-directory: ios/App
        run: pod install --repo-update

      - name: Build iOS workspace
        run: |
          set -euo pipefail
          WORKSPACE="ios/App/App.xcworkspace"
          SCHEME="App"
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath "$PWD/ios/build/DerivedData" \
            build
