name: ios / Build & Upload (manual)

on:
  workflow_dispatch: {}

jobs:
  build-ios:
    name: Build iOS Workspace
    runs-on: macos-latest
    timeout-minutes: 60

    env:
      XCODE_WORKSPACE: ios/App/App.xcworkspace
      XCODE_SCHEME: App
      DERIVED_DATA: ios/build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build web assets
        run: npm run build

      - name: Ensure CocoaPods
        run: |
          pod --version || sudo gem install cocoapods --no-document
          pod --version

      - name: Sync Capacitor (iOS)
        run: npx cap sync ios

      - name: Install Pods
        working-directory: ios/App
        run: pod install --repo-update

      - name: Build iOS workspace (simulator)
        run: |
          set -euo pipefail
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath "$DERIVED_DATA" \
            build

      # Optional: keep build outputs for debugging
      - name: Upload derived data (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-derived-data
          path: ${{ env.DERIVED_DATA }}
