name: iOS CI (Build & Upload)
on:
  workflow_dispatch:
  push:
    branches: [ release/ios-v1 ]
jobs:
  build-upload:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with: { ruby-version: '3.2' }
      - name: Node install
        uses: actions/setup-node@v6
        with: { node-version: '20' }
      - name: Install deps & build web
        run: |
          npm ci
          npm run build
      - name: Install Capacitor iOS toolchain
        run: |
          npm i -D @capacitor/cli @capacitor/assets
          npm i @capacitor/core @capacitor/ios
          npx cap init "TradeLine 24/7" com.apex.tradeline247 --web-dir=dist || true
          npx cap add ios || true
          npx cap copy ios && npx cap sync ios
      - name: CocoaPods
        run: |
          sudo gem install cocoapods -N
          cd ios && pod install --repo-update
      - name: Xcode build (archive)
        run: |
          xcodebuild -workspace ios/App.xcworkspace -scheme App -configuration Release -destination 'generic/platform=iOS' -archivePath $PWD/ios/build/App.xcarchive archive DEVELOPMENT_TEAM=$APPLE_TEAM_ID
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      - name: Export .ipa (automatic signing)
        run: |
          xcodebuild -exportArchive -archivePath ios/build/App.xcarchive -exportOptionsPlist ios/App/exportOptions.plist -exportPath ios/build
        continue-on-error: true
      - name: Fastlane
        run: |
          gem install fastlane -N
          bundle exec fastlane ios beta || fastlane ios beta
        env:
          ASC_API_KEY_ID: ${{ secrets.ASC_API_KEY_ID }}
          ASC_API_ISSUER_ID: ${{ secrets.ASC_API_ISSUER_ID }}
          ASC_API_KEY: ${{ secrets.ASC_API_KEY }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
