name: ci / ios-build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Sync Capacitor iOS project
        run: npx cap sync ios

      - name: Install CocoaPods dependencies
        working-directory: ios/App
        env:
          COCOAPODS_DISABLE_STATS: 'true'
        run: |
          pod repo update
          pod install

      - name: Build iOS workspace
        working-directory: ios/App
        run: |
          set -euo pipefail
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            build
