name: ios / Build Verification

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'ios/**'
      - 'capacitor.config.*'
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
      - 'public/**'

jobs:
  build-ios:
    name: Build iOS Workspace
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build web assets
        run: npm run build

      - name: Sync Capacitor project
        run: npx cap sync ios

      - name: Ensure CocoaPods is available
        run: |
          if ! command -v pod >/dev/null 2>&1; then
            sudo gem install cocoapods --no-document
          fi

      - name: Install CocoaPods dependencies
        working-directory: ios/App
        run: pod install

      - name: Build iOS workspace
        run: |
          set -euo pipefail
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            build
