name: Load Testing

on:
  workflow_dispatch:
    inputs:
      concurrent_users:
        description: 'Number of concurrent users'
        required: false
        default: '10'
      duration:
        description: 'Test duration in seconds'
        required: false
        default: '60'
  schedule:
    # Run weekly on Sundays at 2 AM UTC (low traffic)
    - cron: '0 2 * * 0'

jobs:
  load-test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6
      
      - name: Run load test
        env:
          PROJECT_URL: https://hysvqdwmhxnblxfqnszn.supabase.co
          CONCURRENT_USERS: ${{ github.event.inputs.concurrent_users || '10' }}
          DURATION: ${{ github.event.inputs.duration || '60' }}
          RAMP_UP: '10'
        run: |
          chmod +x scripts/load-test.sh
          ./scripts/load-test.sh
      
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: load-test-results
          path: /tmp/tl247-load-test-summary.json
          retention-days: 30
      
      - name: Comment on commit (if manual)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const summary = JSON.parse(fs.readFileSync('/tmp/tl247-load-test-summary.json', 'utf8'));
            
            const comment = `## 🔥 Load Test Results
            
            **Configuration:**
            - Concurrent Users: ${{ github.event.inputs.concurrent_users || '10' }}
            - Duration: ${{ github.event.inputs.duration || '60' }}s
            
            **Metrics:**
            - P95 Latency: ${summary.metrics.http_req_duration?.values?.['p(95)']?.toFixed(2)}ms
            - Error Rate: ${(summary.metrics.http_req_failed?.values?.rate * 100)?.toFixed(2)}%
            - Total Requests: ${summary.metrics.http_reqs?.values?.count}
            
            See full results in workflow artifacts.
            `;
            
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: comment
            });
