name: Smoke Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install Playwright browsers on the runner
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install deps
        run: npm ci || npm i

      - name: Build app
        run: npm run build

      - name: Start preview server
        run: npm run preview &

      - name: Run CTA smoke tests
        run: npx playwright test tests/cta-smoke.spec.ts --trace on

      - name: Upload Playwright artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: playwright-report
          if-no-files-found: ignore
          retention-days: 7
